### ISSUE TITLE
External ansible repo

### ISSUE THREAD

**Issue by Stuey2** [rics3n/drone-ansible#2]
Is there any way to reference and use an external ansible repo, which contains a variety of roles, playbooks, etc and obviously one or more inventory files?

Put the other way, must you maintain an inventory and playbook file in the project that you want to use drone-ansible from?

**Comment by thetooth** [comment]
Yes, see http://docs.drone.io/cloning/ , setting this will have just the .drone.yml file run from the repo that triggers the build while the working code base can be from anywhere. For more than one source, just add multiple command entries with their full git clone commands.

```
pipeline:
  clone:
    git:
      image: plugins/git
      command:
        - git clone foo
        - git clone bar
```
