### ISSUE TITLE
secrets: [ssh_key]

### ISSUE THREAD

**Issue by mr-shibaev** [rics3n/drone-ansible#8]
Hello!
In the secrets I added ssh_key
Here is my code:
```
deploy-staging:
    image: rics3n/drone-ansible:2
    secrets: [ ssh_key ]
    playbook: ansible/playbook.yml
    inventory_path: ansible/inventory
    inventory: hosts
```
In the secrets I added ssh_key
Tell me why ssh_key does not work
